### ISSUE TITLE
Host the plugin in the Jenkins org

### ISSUE THREAD

**Issue by kohsuke** [awslabs/aws-codedeploy-plugin#1]
I'd like to encourage that the plugin be hosted in the Jenkins org. [The process is outlined here](https://wiki.jenkins-ci.org/display/JENKINS/Hosting+Plugins), and you can see that [other AWS related plugins](https://github.com/jenkinsci/aws-beanstalk-publisher-plugin) are already there.

This way we can help you with releases, bug fixes, and improvements. This will also help us make this plugin available from the update center to users, so that people won't have to build it from source.

If you are OK with it, I'm happy to do all the work, including 1.0 release assuming that's what you want. Or if you want to set up the release process on your own, I can work with you, too.

**Comment by Jmcfar** [comment]
I'm closing this out as I do not believe there is anything left to do. Please feel free to re-open if needed.

Thanks!
