### ISSUE TITLE
Plugin does not support .NET published code

### ISSUE THREAD

**Issue by scojomodena** [awslabs/aws-codedeploy-plugin#10]
It seems the plugin only support the build artifacts. For an ASP.NET project, the project is not just built, but published. The published build is in a different location than the workspace. Can the plugin allow me to just specify the folder that I want it to package up instead of just taking the workspace?

**Comment by Jmcfar** [comment]
Hi,

Is the ASP.NET project published under child folder in the workspace? 

If so, the 1.6 version of the plug in released this week should unblock your use case. It allows you specify a subfolder under the project work-space to use as the bundle base directory. 

If it is not a subfolder, can you give an example layout for how your work-space and published directories are set up?

**Comment by scojomodena** [comment]
No, they are separate. I have a publish config that is to a different drive/folder entirely.

**Comment by Jmcfar** [comment]
The plugin now allows you to specify the folder you want to bundle up as part of the deployment. Please feel free to re-open if this does not solve your use case.
