### ISSUE TITLE
Polling Timeout not honored

### ISSUE THREAD

**Issue by mattlevin** [awslabs/aws-codedeploy-plugin#13]
Looks like the polling timeout is always set to the default 900s. Looking at the code I think its just a config key mismatch

"pollingTimeout" in config
https://github.com/awslabs/aws-codedeploy-plugin/blob/master/src/main/resources/com/amazonaws/codedeploy/AWSCodeDeployPublisher/config.jelly#L34

vs.

"pollingTimeoutSec" in code
https://github.com/awslabs/aws-codedeploy-plugin/blob/master/src/main/java/com/amazonaws/codedeploy/AWSCodeDeployPublisher.java#L74

**Comment by jmmen1** [comment]
I was able to work around the issue by manually editing the timeout value in the config.xml, and then reloading the Jenkins configuration from disk.

**Comment by Jmcfar** [comment]
Hi,

Thanks for the bug report. We've identified and fixed the issue in the latest release of the plugin which will be released shortly.

**Comment by Jmcfar** [comment]
This should be fixed in the 1.6 version of the plugin. Please re-open and let us know if you're still experiencing any problems.
