### ISSUE TITLE
Add new regions

### ISSUE THREAD

**Issue by gblachonupg** [awslabs/aws-codedeploy-plugin#15]
Is it possible to add Europe regions to codedeploy plugin following the availability of Codedeploy in Europe Today ?

**Comment by benjaminos** [comment]
+1 for eu-west-1 support.

**Comment by Jmcfar** [comment]
Hi,

The 1.6 version of the plugin released this week should include support for all current CodeDeploy regions. Please re-open and let us know if you have any problems using it!
