### ISSUE TITLE
Feature: Push revision (without deployment)

### ISSUE THREAD

**Issue by franklanganke** [awslabs/aws-codedeploy-plugin#20]
As Ops I would like to push a revision (without deploying) after a successful build so I can trigger a deployment through the CLI or Console at a later date.

**Comment by jmmen1** [comment]
I would like to be able to push a revision as well. This would allow our organization the ability for one team to create the revision, and then handoff deployment of that revision to another team.

**Comment by neilhunt1** [comment]
Agreed. It would be better if this plugin was structurally divided into two: one to create a revision, one to push it to a deployment group while specifying a revision. That would also satisfy the item on your TODO file list: * Add ability to deploy to multiple deployment groups. We could add n deployment groups pointing to same revision location
