### ISSUE TITLE
Can't parameterize the deployment group

### ISSUE THREAD

**Issue by jimadamsss** [awslabs/aws-codedeploy-plugin#24]
I have a set up deployment groups that I want to automation Jenkins. Each build is exactly the same except for the name of the deployment group. I tried to create a parameterized build but the fields for the CodeDeploy plugin do not substitute from the parameters. Here is the console output:
CODEDEPLOYGROUP=CodeDeployDesignGroup-group-Jim

[EnvInject] - Variables injected successfully.
Failed CodeDeploy post-build step; exception follows.
Cannot find deployment group named '${CODEDEPLOYGROUP}'
java.lang.IllegalArgumentException: Cannot find deployment group named '${CODEDEPLOYGROUP}'

**Comment by cosmincatalin** [comment]
I will look into making this happen. I have already added support for variables to the S3 path.

**Comment by jordiclariana** [comment]
This feature would be really apreciated. +1

**Comment by aerostitch** [comment]
Having the same issue. It would indeed be really appreciated! +1 :)

**Comment by jakeleveroni** [comment]
It would be great, I would also appreciate the add as well :)

**Comment by suryanarayanan** [comment]
Merged https://github.com/awslabs/aws-codedeploy-plugin/pull/35 to use environment variable for deployment group.

**Comment by jimadamsss** [comment]
I see a fix was pushed for this but I guess my request wasn't clear enough. I need ALL parameters to the plugin to all the use of environment variables. I see that issue #42 was added to address just one more parameter but, really, all parameters should be able to be fixed at run time.

**Comment by Jmcfar** [comment]
Hi, 

The App Name, Deployment Group Name, Deployment Config Name, S3 Bucket and S3 Prefix fields should now all support parameterization as of version 1.8. If there are any we missed that you'd like to parameterize please feel free to re-open.
