### ISSUE TITLE
Nothing displays when selecting Deploy an Application to AWS Code Deploy

### ISSUE THREAD

**Issue by neilhunt1** [awslabs/aws-codedeploy-plugin#26]
Within my job configuration, when I select "Deploy and Application to AWS CodeDeploy" from the post-build action dropdown, nothing happens. I am not presented with the parameters to deploy my app. I looked in my javascript console and get the following error in my browser:

GET http://internal-awslbjenkinsed01-572120769.us-east-1.elb.amazonaws.com/job/…l-awslbjenkinsed01-572120769.us-east-1.elb.amazonaws.com%2F&credentialsId= 504 (GATEWAY_TIMEOUT)

I have confirmed this with multiple users and multiple browsers, with both 1.5 and 1.6 of aws-codedeploy-plugin. We are running Jenkins 1.596.2

**Comment by neilhunt1** [comment]
Also confirmed on 1.609.1
Any updates on this?

**Comment by kevhu** [comment]
I'm seeing this as well running Jenkins 1.617

**Comment by yubangxi** [comment]
HI,

Thanks for the feedback, we will look into this issue. 
We will update this once we find the root cause.

Thanks!

**Comment by neilhunt1** [comment]
This appears to have been the case when operating behind a proxy server. Once I added the proxy configuration to Manage Jenkins > Configure System and under the AWS CodeDeploy Credentials section, I was able to operate again. Closing for now.
