### ISSUE TITLE
AWS Secret Access Key / Secret not saving

### ISSUE THREAD

**Issue by mkrokosz** [awslabs/aws-codedeploy-plugin#3]
It appears the AWS Access Key / Secret fields do not save properly.  No matter what I put in the field, they always come back empty.  This is true on both the global as well as job-specific settings. 

Not sure if related or a different problem, but when trying to use alternative method of injecting environment variables for AWS_ACCESS_KEY and AWS_SECRET_KEY, the plugin does not seem to recognize and use them either.

**Comment by tubaguy50035** [comment]
+1.  Experiencing the same issue.

**Comment by volker-fr** [comment]
Same problem with the saving here. Actually the codes uses AWSSecurityTokenServiceClient which uses different variables (see http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/securitytoken/AWSSecurityTokenServiceClient.html): AWS_ACCESS_KEY_ID and AWS_SECRET_KEY. But I don't seem to have success with them, too.

**Comment by tglenister** [comment]
I am also having the same issue. Any ideas when the fix will be merged and available on the Jenkins Update Server?

**Comment by tubaguy50035** [comment]
@afitzgibbon Can this get some love?

**Comment by laltomar-cn** [comment]
I am also seeing this issue, Any ETA when the fix will be available. Also are there any workarounds.

**Comment by Jmcfar** [comment]
Thank you for bringing this to our attention. We've reproduced the issue and are working on a fix for it. We will post an update once the fix is rolled out.
