### ISSUE TITLE
Provide change log for plugin

### ISSUE THREAD

**Issue by patrickdlee** [awslabs/aws-codedeploy-plugin#34]
It would be very helpful to have a change log that summarizes each release of the plugin.  This could include new features, bug fixes, enhancements, or other information.  The de facto convention appears to be a file called CHANGELOG.md in the root of a repository.  Here's some unofficial info about GitHub change logs (it even has its own change log)...

https://github.com/olivierlacan/keep-a-changelog/blob/gh-pages/README.md

On a related note, each release could be tagged in order to populate this list...

https://github.com/awslabs/aws-codedeploy-plugin/releases

And finally, thank you for providing a REALLY useful plugin!  I really appreciate it.

**Comment by suryanarayanan** [comment]
Instead of maintaining a change log we'll start tagging all future releases with a brief description of updates and bug fixes. Thanks for your feedback.

**Comment by patrickdlee** [comment]
Perfect. Thank you!
