### ISSUE TITLE
Documentation on "Use temporary credentials"

### ISSUE THREAD

**Issue by dashfwd** [awslabs/aws-codedeploy-plugin#39]
The "Use temporary credentials" feature of the plugin needs better documentation.

If this uses the AWS Security Token Service, could you provide some example of how to set that up?  It looks like the Security Token Service needs to be specifically enabled for each region, and then you need to create a Trust Policy (http://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user_externalid.html).  

I'm not at all clear on what role I need, what permissions are needed for that role, or how to configure the trust policy -- could you add that to the docs?

Also The help text has this documentation:

> This plugin uses temporary access keys via the AWS Security Token Service. For instructions on setting this up, see the help text on the "IAM Role ARN" field above

There is no "IAM Role ARN" field above to refer to, and thus no additional help text.

Thank you.

**Comment by suryanarayanan** [comment]
I installed the latest version of this plugin (1.8) and the IAM Role ARN field help text clearly explains about the role and permissions required. Here's the content of that help text

    In order to keep your application(s) more secure, this plugin only uses temporary credentials via STS, scoped to each application. To set this up: 
    Log into the AWS Management Console, and navigate to the Identity and Access Management console.
    Click on Roles, then click Create New Role.
    Give an appropriate name for this role (for example, "JenkinsCodeDeployProject").
    In the "Select Role Type" screen, click "Role for Cross-Account Access" then select Allows IAM users from a 3rd party AWS account to access this account.
    The account and external IDs for this Jenkins project are listed below
    In the policy screen, select Custom Policy and copy-paste the following policy:
        {"Version": "2012-10-17", "Statement": [{"Effect": "Allow", "Action": ["codedeploy:*", "s3:*"], "Resource": "*"}]}
    Click Create Role, then copy-paste the Role ARN into the below field.
    Click the Test Connection button to ensure that the permissions are set up properly.
