### ISSUE TITLE
Use temporary credentials doesn't work as expected

### ISSUE THREAD

**Issue by nwalke** [awslabs/aws-codedeploy-plugin#4]
When I add CodeDeploy as a post build task and click temporary credentials, it does not spit out an AWS account ID.  It does give me an external ID.

**Comment by amuniz** [comment]
Issue confirmed using:
 - Jenkins 1.580.2
 - Debian 7
 - CodeDeploy 1.3

**Comment by Jmcfar** [comment]
Thank you for bringing this to our attention. We've identified the issue and are working on a fix for it. We will post an update once the fix is rolled out.

**Comment by Jmcfar** [comment]
We have pushed updated source to resolve a related issue into the repository but it is not yet available from the Jenkins repository. 

If you see external ID but not an AWS Account ID using CodeDeploy 1.3 it likely means your instance does not have AWS credentials configured. The temporary credentials option still needs AWS Credentials to call AssumeRole to get the temporary credentials with reduced permissions.

Once you configure the Jenkins server with default AWS credentials, you should see the account id show up.

**Comment by tubaguy50035** [comment]
What if the Jenkins server is not an EC2 instance, but an on-premise machine?  Will temporary credentials not work then?

**Comment by Jmcfar** [comment]
Any of the default provider chain methods listed on http://docs.aws.amazon.com/AWSSdkDocsJava/latest/DeveloperGuide/credentials.html should work (although if you are not using EC2, you won't be able to use "Instance profile credentials")

**Comment by tubaguy50035** [comment]
@Jmcfar Any updates on when we can expect this update through the Jenkins repository?

**Comment by Jmcfar** [comment]
We just finished pushing the new plugin to the Jenkins update repository. The current plugin list is only updated every 6 hours, so it may not show up immediately, but should be there by tomorrow.

The latest release version for the CodeDeploy plugin is 1.5, so once you pull that in you should be up to date.

**Comment by tubaguy50035** [comment]
Awesome!  Very excited to not have to use my own bash scripts to interface with the CLI.

**Comment by BStokes** [comment]
Getting an error when trying the temp permissions when following the steps provided.

Connection test failed with error: The request signature we calculated does not match the signature you provided. Check your key and signing method. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; 

The error would imply a time differentail between AWS and the Jenkins server, and have verified that the times are synced.  Any suggestions on how I might troubleshoot/correct this error?

**Comment by suryanarayanan** [comment]
@BStokes: Did you specify a valid S3 bucket name?

**Comment by BStokes** [comment]
Issue has been resolved for some time now.  Thx for the follow up.
