### ISSUE TITLE
CodeDeploy application name cannot be parameterized

### ISSUE THREAD

**Issue by velinath** [awslabs/aws-codedeploy-plugin#42]
Similar to #24, probably - I have a CI pipeline architecture that requires multiple CodeDeploy application names, and the plugin is telling me that the parameter is not recognized.(`Cannot find application named '$CODEDEPLOY_APPNAME'`).

Any way to fix this at this time?

**Comment by Jmcfar** [comment]
Hi,

This should now be possible in the version 1.8 or higher of the CodeDeploy Plugin.

**Comment by velinath** [comment]
Thank you so much!
