### ISSUE TITLE
ETag mismatch in CodeDeploy

### ISSUE THREAD

**Issue by bgardella** [awslabs/aws-codedeploy-plugin#45]
CodeDeploy is not liking the application bundle created by this plugin.  I'm getting the following error from CodeDeploy:

"The request signature we calculated does not match the signature you provided. Check your key and signing method."

**Comment by bgardella** [comment]
I solved this mystery.  I was putting a subdirectory in my S3 Bucket field.  And since the combination of S3 Bucket + S3 Prefix produces a valid S3 path, the UI and the SDK implementation does not prevent the file from being uploaded to S3.  But the checksum produced is completely horked.

I'm going to submit a PR that would forbid any slashes from being set in the S3 bucket field.

**Comment by bgardella** [comment]
PR submitted for your review.

**Comment by aws-turpiej** [comment]
Closing in favor of https://github.com/awslabs/aws-codedeploy-plugin/pull/47
