### ISSUE TITLE
Old Builds

### ISSUE THREAD

**Issue by SonyDavid** [awslabs/aws-codedeploy-plugin#55]
There doesn't seem to be a clean way to remove old builds. My initial thought was use the S3 versioning. However since the zip file upload is different name each time, that wont work. Also can't use time based removal as if you have a long period with no build, it might delete the current version.

**Comment by gaohan137** [comment]
Maybe setup a cron job and also keep track of current version. Then remove other unnecessary files other than the current version?

**Comment by tkokev** [comment]
Would be cool if CodeDeploy had a native max build or a age off feature.

**Comment by gaohan137** [comment]
We'll bring this to our PM's attention and prioritize it accordingly. Thanks for the feature request!
