### ISSUE TITLE
Add support for cn-north-1

### ISSUE THREAD

**Issue by xiaochuan-du** [awslabs/aws-codedeploy-plugin#70]
As you may know, codedeploy has been lauched in China, thus it would be great if we can use this plugin soon. Thanks.

**Comment by ambareesha** [comment]
We are working on fixing this. Thank you for your patience.

**Comment by gdeblina** [comment]
Jenkins plugin is now available in China

**Comment by xiaochuan-du** [comment]
Thanks.

**Comment by cncoder** [comment]
Hi Team,

The China (Ningxia) Region, operated by NWCD, supports AWS Codedeploy last year. Could you support this region now?

Please see this PR for more detail. https://github.com/awslabs/aws-codedeploy-plugin/pull/101

**Comment by Levi-Lo** [comment]
Could you support cn-northwest-1 region ?
