### ISSUE TITLE
Aws green blue 

### ISSUE THREAD

**Issue by anwoolterton** [awslabs/aws-codedeploy-plugin#73]
Hi,

When will this plug-in support green blue deployments, looking at Jenkins its not clear if it does or if any other changes are required.

**Comment by rmurillo21** [comment]
Wouldn't that be part of the deployment group configuration rather than the plug-in?

**Comment by feverLu** [comment]
Yeah Blue Green deployment now is officially supported: https://aws.amazon.com/blogs/devops/performing-bluegreen-deployments-with-aws-codedeploy-and-auto-scaling-groups/. This is a new deployment type and needs to be configured on the deployment group level.
