### ISSUE TITLE
Help text in global configuration "ERROR: Failed to load help file: Not Found"

### ISSUE THREAD

**Issue by tubaguy50035** [awslabs/aws-codedeploy-plugin#8]
This is with version 1.5 of the plugin and Jenkins 1.599.

![screen shot 2015-03-05 at 12 17 42 am](https://cloud.githubusercontent.com/assets/1617620/6500140/1caaeea6-c2cd-11e4-8ef6-d5dd3248b391.png)

**Comment by Jmcfar** [comment]
Thanks for the bug report! We've identified the issue and are working on a fix.

**Comment by Jmcfar** [comment]
Sorry about the delay on responding - This should be fixed with the 1.6 version of the plugin that went out this week. Please feel free to re-open if you have any issues.
