### ISSUE TITLE
Allow deployment from github

### ISSUE THREAD

**Issue by veilig2000** [awslabs/aws-codedeploy-plugin#9]
are there any plans to allow deployment from github also?

**Comment by aws-troutman** [comment]
Hi, 

This is achievable today. Here is a blog post we did going through the steps to set this up:
https://blogs.aws.amazon.com/application-management/post/Tx33XKAKURCCW83/Automatically-Deploy-from-GitHub-Using-AWS-CodeDeploy

**Comment by veilig2000** [comment]
I'm a little confused, this article makes no mention of the jenkins plugin.  I'm aware that you can already do code deployments via github - in fact I've already done that.  But what my question was (that is attached to this AWS CodeDeploy Jenkins Plugin repo)  are there any plans to allow deployments via this plugin from github also, as there currently appears no way to facilitate this.

**Comment by Jmcfar** [comment]
Hi,

Can you provide some more information on what you'd like to do? The current AWS CodeDeploy Jenkins plugin can work on any source repository for Jenkins projects, so you can set up a project to pull from GitHub, build the application and then push to an S3 bucket for CodeDeploy to use. Is there something else you'd like to do on Jenkins that isn't possible with the current GitHub integration?

Thanks!

**Comment by veilig2000** [comment]
ya - but why do I have to push up to S3, just to deploy back out to an
instance?  Why can't it just pull from github and use existing
functionality that codedeploy already allows.  Maybe I'm not seeing an
added benefit of doing it that way?

Also, I know you allow deploying from S3 to the US_EAST_1 region - but
don't you also support deploying to US_WEST_2?    Per your S3 pricing model
wouldn't you get charged if you deployed to any region other than the
northern Virginia region (perhaps I mis-read something about this)?  I do
realize the cost is peanuts, but still the principal of the matter.

I guess I didn't understand why code deploy does facilitate multiple paths
to achieve the same outcome, but we can't leverage one via this plugin?

thanks for following up on this.

Thanks,
Jamie K.

**Comment by Jmcfar** [comment]
The plugin bundles up the build artifacts from the Jenkins job and uploads / deploys those - If you wanted to use a GitHub repository as a source for the build artifacts the Jenkins job would need to push the build output back to GitHub before creating a GitHub deployment in AWS CodeDeploy.

Are you using a project that doesn't produce any build artifacts and want the original source commit used by the Jenkins job deployed?

**Comment by veilig2000** [comment]
correct, no artifacts.

My jenkins job clones from github and runs metrics and tests on the code.
Nothing should really need to change about the code locally that I could
bundle into an artifact and deploy - so I should just be able to pull the
updates from github directly.

I'm already using codedeploy, but its manual to deploy or workaround's to
do the same thing in a build script for jenkins.

my appspec file moves the code I need into the correct spot during
deployment, but then calls some scripts that have to be run on the server
itself.  so I don't really have a need to bundle anything up and push to
two spots.

Thanks,
Jamie K.

**Comment by NoodlesNZ** [comment]
Anything further on this? I started writing a PR for this, but I haven't written Java in a long time. Essentially it would be using https://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/com/amazonaws/services/codedeploy/model/GitHubLocation.html with a GitHub repository and a commit id (sha1). I'm sure there's a bunch of changes to be made to make this work as the plugin assumes that artifacts are created and always uploaded to the S3 bucket for deployment.

I would find this enhancement extremely useful as our pipelines don't create any artifacts, only tag releases in git.

**Comment by Jmcfar** [comment]
We do not have anything in flight currently for this feature request. We're happy to review a pull request if you would like to add the functionality. The approach you mention sounds reasonable.

**Comment by NoodlesNZ** [comment]
Ok, I'll give it a shot. It'll be a hack though, hopefully it will make enough sense for someone to do it properly. :)

**Comment by NoodlesNZ** [comment]
Ok, something like #81 ?

**Comment by Jmcfar** [comment]
In order to make this seamless, you'll want to pull the GitHub information from the build itself (otherwise the user will need to edit the plugin properties for each new commit to the repository). For the plugin jelly/config you'll just want a checkbox to enable deploying from source to toggle the new behavior on/off.

**Comment by NoodlesNZ** [comment]
It makes more sense when you use it in pipeline as code, e.g.

```
stage('Deploy') {
      steps {
        input "Deploy?"
        
        withCredentials([[$class: 'AmazonWebServicesCredentialsBinding', credentialsId: 'AWSCreds',
                        accessKeyVariable: 'awsAccessKey', secretKeyVariable: 'awsSecretKey']]) {
    
          step([$class: 'AWSCodeDeployPublisher',
            applicationName: 'site.com',
            awsAccessKey: env.awsAccessKey,
            awsSecretKey: env.awsSecretKey,
            credentials: 'awsAccessKey',
            deploymentGroupAppspec: false,
            deploymentGroupName: 'Production-site.com',
            deploymentConfig: 'CodeDeployDefault.OneAtATime',
            deploymentMethod: 'deploy',
            includes: '**',
            region: 'us-east-1',
            githubRepository: 'example/site',
            githubCommitId: env.GIT_COMMIT,
            waitForCompletion: true])
        }
      }
    }
```

**Comment by Jmcfar** [comment]
Understood! Could you add help html snippets for the two new fields indicating that they are intended to be used in the pipelining mode?

Other than that, looks good. If you could update the PR w/ what testing you've locally and confirm that you're contributing this under Apache 2.0 License, I can rereview and hopefully merge it after the update.

**Comment by NoodlesNZ** [comment]
Ok, this has been merged into master now, you can probably close off this issue. Thanks :)
